title: A Coffee Fueled Adventure
description: A Beginner's Guide to Programming in CoffeeScript
baseurl: /coffee-adventure
exclude: [apps/, chapters/, LICENSE.md, README.md, gulpfile.coffee]
kramdown:
  input: GFM
sass:
  style: compressed
