title: A Coffee Fueled Adventure
description: A Beginner's Guide to Programming in CoffeeScript
baseurl: /coffee-adventure
exclude:
  - node_modules/
  - apps/
  - chapters/
  - exercises/
  - answers/
  - LICENSE.md
  - README.md
  - package.json
  - bower.json
  - gulpfile.coffee
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
collections:
  chapters:
    output: true
    permalink: /chapters/:path/
  exercises:
  answers:
